### ISSUE TITLE
Respect .dockerignore file

### ISSUE THREAD

**Issue by mkarpusiewicz** [awkspace/dockit#2]
Currently all the files are mounted which make take a while with `node_module`,  or any other big directories that are ignored during normal docker build and probably we do not want them inside anyways. Maybe an additional option for this case would make sense?

**Comment by awkspace** [comment]
I've added some primitive `.gitignore` and `.dockerignore` awareness in #3. Removals take place before the big `chown`, which should cut down on both space and time when mounting.

Since I can't rely on the image having `git` or `docker`, I'm ignoring files based off of shell glob expansion, which is an approximation but should cover most use cases.

If you've got a large project to test mounting with, let me know if this improves it!

**Comment by mkarpusiewicz** [comment]
@awkspace That's great to hear, thanks! I'm on vacation right now, I'll try it when I get home and give you an update.
